name: Master CI/CD

on: 
  push:
    branches: 
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [10.x, 12.x]

    steps:
    - uses: actions/checkout@v1
      with:
        fetch-depth: 1
      
      env:
        CI: true
      
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
      
    - name: npm install
      run: npm ci

    - name: npm lint
      run: npm run lint

    - name: npm build
      run: npm run build

    - name: npm test
      run: npm run test-ci
      
    - name: If Highest Node Version Then Deploy 
      if: success() && matrix.node-version == '12.x'
      uses: JamesIves/github-pages-deploy-action@releases/v3
      with:
        ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
        BASE_BRANCH: master # The branch the action should deploy from.
        BRANCH: gh-pages # The branch the action should deploy to.
        FOLDER: dist/budget # The folder the action should deploy.
